### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by oliszymanski** [oliszymanski/system-wozkowy#4]
generating calendar:
- [x] get all days for wittnessing (tuesday, thursday, friday and saturday)
- [x] create templates for each day with
    - [x] date
    - [x] location
    - [x] time
- [x] generate for entire month

**Comment by oliszymanski** [comment]
all done. Waiting for the proper dyspozycyjnosc.csv file to implement
