### ISSUE TITLE
New To-do

### ISSUE THREAD

**Issue by oliszymanski** [oliszymanski/system-wozkowy#6]
- [ ] adjust dyspozycyjnosc.csv to the primary dyspozycyjnosc.csv structure:
    - [ ] get .csv file from .xlsx
- [ ] organise the code - split into files
- [ ] Models (assigned: @Noruf )
